openapi: 3.0.0

info:
  title: Dataseries and readings
  description: Original version of the dataseries and readings API
  version: 1.0.0

servers:
  - url: http://localhost/v1
    description: Development environment

paths:
  /dataseries/summaries:
    get:
      description: Return summaries for all dataseries
      responses:
        '200':
          description: A JSON array of data series summaries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataSeriesSummary'
  /dataseries/{dataSeriesId}/summary:
    get:
      operationId: GetDataseriesSummariesDataSeriesId
      description: Return summary for requested dataseries
      parameters:
        - in: path
          name: dataSeriesId
          required: true
          schema:
            type: integer
            format: int64
          description: Id of the dataseries
      responses:
        '200':
          description: A data series summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSeriesSummary'
  /dataseries/{dataSeriesId}/readings:
    get:
      description: Query readings
      parameters:
        - in: path
          name: dataSeriesId
          required: true
          schema:
            type: integer
            format: int64
          description: Id of the dataseries
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            maximum: 500
            minimum: 1
            default: 100
          description: Maximum number of readings to return
      responses:
        '200':
          description: A JSON array of reading objects matching the query parameters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reading'
    post:
      description: Add new value to the dataseries
      parameters:
        - in: path
          name: dataSeriesId
          required: true
          schema:
            type: integer
            format: int64
          description: Id of the dataseries
      requestBody:
        description: A new value and valid API key for the given data series
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReading'
      responses:
        '201':
          description: The reading was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
        '401':
          description: API key missing of not valid
        '400':
          description: The value could not be stored
  /series/{dataSeriesId}/add:
    post:
      description: Legacy endpoint for adding a reading to the dataseries
      parameters:
        - in: path
          name: dataSeriesId
          required: true
          schema:
            type: integer
            format: int64
          description: Id of the dataseries
      requestBody:
        description: A new value and valid API key for the given data series
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ReadingForm'
      responses:
        '201':
          description: The reading was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
        '401':
          description: API key missing of not valid
        '400':
          description: The value could not be stored


components:
  schemas:
    DataSeriesSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: datetime
        updatedAt:
          type: string
          format: datetime
        currentValue:
          type: string
        minValue:
          type: string
        maxValue:
          type: string
        dataSeriesId:
          type: integer
          format: int64
        dataSeriesDescription:
          type: string
        dataSeriesName:
          type: string
        dataSeriesLabel:
          type: string
      required: [ id, dataSeriesId ]
    Reading:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: datetime
        updatedAt:
          type: string
          format: datetime
        value:
          type: string
      required: [ id, createdAt, value ]
    NewReading:
      type: object
      properties:
        value:
          type: string
        apiKey:
          type: string
      required: [ value, apiKey ]
    ReadingForm:
      type: object
      properties:
        value:
          type: string
        api_key:
          type: string
      required: [ value, api_key ]
